import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header"

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen overflow-y-scroll scrollbar-thin scrollbar-thumb-accent scrollbar-thumb-rounded scrollbar-track-transparent scroll-smooth">
      <body
        className={`${jetbrainsMono.variable} antialiased bg-primary text-slate`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
