import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header"
import { ShootingStars } from "../components/ui/shooting-star";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen overflow-y-scroll overflow-x-hidden scrollbar-thin scrollbar-thumb-accent scrollbar-thumb-rounded scrollbar-track-transparent scroll-smooth">
      <body
        className={`${jetbrainsMono.variable} antialiased bg-primary text-slate`}
      >
        <Header />
        {children}
        <footer className="pb-1 text-center text-xs pointer-events-none select-none pt-10 lg:pt-16 xl:pt-20">~ABDULLAH AL SAYEF~</footer>
        <div className="-z-30 fixed top-0 h-screen left-0 w-screen">
            <ShootingStars starColor="#22b7f7" trailColor="#22b7f7" className=""/>
        </div>
        
      </body>
    </html>
  );
}
